"use client"

import { useState, useCallback, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Card, CardContent } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Switch } from "@/components/ui/switch"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import {
  ArrowLeft,
  Download,
  ChevronLeft,
  ChevronRight,
  Palette,
  Layout,
  FileText,
  Check,
  Loader2,
  Sparkles,
  ImageIcon,
  Trash2,
  Shuffle,
  Images,
  AlignLeft,
  Save,
  Cloud,
  Plus,
  Minus,
  Settings,
  User,
  Send,
  Undo,
  Redo,
  Share2,
  PanelLeftClose,
  PanelLeft,
  Type,
} from "lucide-react"
import { SlidePreview } from "@/components/slide-preview"
import { ThemePicker } from "@/components/theme-picker"
import { LayoutPicker } from "@/components/layout-picker"
import type { CarouselData, CarouselSlide, CarouselTheme, LayoutType, CustomText } from "@/lib/types"
import { DEFAULT_THEMES, LAYOUT_OPTIONS, assignSlideLayouts } from "@/lib/types"

interface CarouselEditorProps {
  initialData: CarouselData
  projectId?: string | null
  onBack: () => void
}

export function CarouselEditor({ initialData, projectId: initialProjectId, onBack }: CarouselEditorProps) {
  const [slides, setSlides] = useState<CarouselSlide[]>(initialData.slides)
  const [currentSlide, setCurrentSlide] = useState(0)
  const [theme, setTheme] = useState<CarouselTheme>(initialData.theme || DEFAULT_THEMES[0])
  const [copied, setCopied] = useState(false)
  const [isAdapting, setIsAdapting] = useState(false)
  const [isGeneratingAllImages, setIsGeneratingAllImages] = useState(false)

  // Sidebar state
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const [aiPrompt, setAiPrompt] = useState("")
  const [titleEnabled, setTitleEnabled] = useState(true)
  const [descriptionEnabled, setDescriptionEnabled] = useState(true)



  // Branding state - initialize from initialData if available
  const [brandName, setBrandName] = useState(initialData.brandName || "Your Name")
  const [brandHandle, setBrandHandle] = useState(initialData.brandHandle || "@your_linkedin_handle")
  const [brandImage, setBrandImage] = useState<string | null>(initialData.brandImage || null)

  const hasAutoGeneratedRef = useRef(false)

  // Auto-save state
  const [projectId, setProjectId] = useState<string | null>(initialProjectId || null)
  const [isSaving, setIsSaving] = useState(false)
  const [lastSaved, setLastSaved] = useState<Date | null>(null)
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null)

  // Save project function
  const saveProject = useCallback(async () => {
    setIsSaving(true)
    try {
      const response = await fetch("/api/projects", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: projectId,
          topic: initialData.topic,
          slides,
          theme,
          brandName,
          brandHandle,
          brandImage,
        }),
      })

      if (response.ok) {
        const data = await response.json()
        if (!projectId && data.project?.id) {
          setProjectId(data.project.id)
        }
        setLastSaved(new Date())
      }
    } catch (error) {
      console.error("Failed to save project:", error)
    } finally {
      setIsSaving(false)
    }
  }, [projectId, initialData.topic, slides, theme, brandName, brandHandle, brandImage])

  // Debounced auto-save
  useEffect(() => {
    // Clear existing timeout
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current)
    }

    // Set new timeout for auto-save (2 seconds after last change)
    saveTimeoutRef.current = setTimeout(() => {
      saveProject()
    }, 2000)

    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current)
      }
    }
  }, [slides, theme, brandName, brandHandle, brandImage, saveProject])

  const updateSlide = useCallback((index: number, updates: Partial<CarouselSlide>) => {
    setSlides((prev) => prev.map((slide, i) => (i === index ? { ...slide, ...updates } : slide)))
  }, [])

  const goToSlide = (index: number) => {
    setCurrentSlide(Math.max(0, Math.min(index, slides.length - 1)))
  }

  const generateBackgroundImage = async (slideIndex: number) => {
    const slide = slides[slideIndex]
    updateSlide(slideIndex, { isGeneratingImage: true })

    // Console logging for tracking
    console.log(`\n========== IMAGE GENERATION START ==========`)
    console.log(`📸 Generating image ${slideIndex + 1}/${slides.length}`)
    console.log(`📝 Topic: ${initialData.topic}`)
    console.log(`📌 Slide Heading: ${slide.heading}`)
    console.log(`🖼️ Suggested Image: ${slide.suggested_image}`)
    console.log(`⏰ Started at: ${new Date().toLocaleTimeString()}`)
    console.log(`============================================\n`)

    try {
      const response = await fetch("/api/generate-image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic: initialData.topic,
          slideHeading: slide.heading,
          suggestedImage: slide.suggested_image,
        }),
      })

      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.error || "Failed to generate image")
      }

      const data = await response.json()
      console.log(`✅ Image ${slideIndex + 1}/${slides.length} generated successfully!`)
      console.log(`🔗 Image URL: ${data.imageUrl}`)
      console.log(`⏰ Completed at: ${new Date().toLocaleTimeString()}\n`)

      updateSlide(slideIndex, {
        backgroundImageUrl: data.imageUrl,
        suggested_image: data.generatedPrompt || slide.suggested_image,
        isGeneratingImage: false,
      })
    } catch (error) {
      console.error(`❌ Failed to generate image ${slideIndex + 1}/${slides.length}:`, error)
      updateSlide(slideIndex, { isGeneratingImage: false })
      alert(error instanceof Error ? error.message : "Failed to generate image")
    }
  }

  const generateAllImages = async () => {
    setIsGeneratingAllImages(true)

    // Console logging for tracking batch generation
    console.log(`\n╔══════════════════════════════════════════════╗`)
    console.log(`║     BATCH IMAGE GENERATION START             ║`)
    console.log(`╠══════════════════════════════════════════════╣`)
    console.log(`║ 📝 Topic: ${initialData.topic.substring(0, 35).padEnd(35)}║`)
    console.log(`║ 📊 Total Slides: ${slides.length.toString().padEnd(28)}║`)
    console.log(`║ ⏰ Started: ${new Date().toLocaleTimeString().padEnd(29)}║`)
    console.log(`╚══════════════════════════════════════════════╝\n`)

    // Mark all slides as generating
    setSlides((prev) => prev.map((slide) => ({ ...slide, isGeneratingImage: true })))

    try {
      // Generate images for all slides in parallel
      const promises = slides.map(async (slide, index) => {
        console.log(`🚀 Starting image ${index + 1}/${slides.length}: "${slide.heading}"`)

        try {
          const response = await fetch("/api/generate-image", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              topic: initialData.topic,
              slideHeading: slide.heading,
              suggestedImage: slide.suggested_image,
            }),
          })

          if (!response.ok) {
            const error = await response.json()
            throw new Error(error.error || "Failed to generate image")
          }

          const data = await response.json()
          console.log(`✅ Image ${index + 1}/${slides.length} DONE → ${data.imageUrl}`)
          return { index, imageUrl: data.imageUrl, generatedPrompt: data.generatedPrompt, success: true }
        } catch (error) {
          console.error(`❌ Image ${index + 1}/${slides.length} FAILED:`, error)
          return { index, success: false }
        }
      })

      const results = await Promise.all(promises)

      // Summary logging
      const successCount = results.filter(r => r.success).length
      const failCount = results.filter(r => !r.success).length
      console.log(`\n╔══════════════════════════════════════════════╗`)
      console.log(`║     BATCH IMAGE GENERATION COMPLETE          ║`)
      console.log(`╠══════════════════════════════════════════════╣`)
      console.log(`║ ✅ Successful: ${successCount.toString().padEnd(30)}║`)
      console.log(`║ ❌ Failed: ${failCount.toString().padEnd(34)}║`)
      console.log(`║ ⏰ Completed: ${new Date().toLocaleTimeString().padEnd(27)}║`)
      console.log(`╚══════════════════════════════════════════════╝\n`)

      // Update all slides with results
      setSlides((prev) => prev.map((slide, index) => {
        const result = results.find((r) => r.index === index)
        return {
          ...slide,
          isGeneratingImage: false,
          backgroundImageUrl: result?.success ? result.imageUrl : slide.backgroundImageUrl,
          suggested_image: result?.success && result.generatedPrompt ? result.generatedPrompt : slide.suggested_image,
        }
      }))
    } catch (error) {
      console.error("❌ Batch generation failed:", error)
      setSlides((prev) => prev.map((slide) => ({ ...slide, isGeneratingImage: false })))
    } finally {
      setIsGeneratingAllImages(false)
    }
  }

  useEffect(() => {
    if (!hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true

      // Check if any slide already has a saved image (from database)
      // If images are local paths (start with /uploads/), don't regenerate
      const hasExistingImages = slides.some(
        (slide) => slide.backgroundImageUrl?.startsWith("/uploads/")
      )

      if (!hasExistingImages) {
        generateAllImages()
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const removeBackgroundImage = (slideIndex: number) => {
    updateSlide(slideIndex, { backgroundImageUrl: undefined })
  }

  const toggleDescriptionLength = () => {
    updateSlide(currentSlide, {
      useExtendedDescription: !slides[currentSlide].useExtendedDescription
    })
  }

  const handleSlideLayoutChange = async (newLayout: LayoutType) => {
    const currentSlideData = slides[currentSlide]
    const previousLayout = currentSlideData.layout || "centered"

    const prevConfig = LAYOUT_OPTIONS.find((l) => l.id === previousLayout)
    const newConfig = LAYOUT_OPTIONS.find((l) => l.id === newLayout)

    // Auto-switch Short/Long description based on layout's content size
    const useShortDesc = newConfig?.contentSize === "compact"

    // Update layout and description toggle immediately
    updateSlide(currentSlide, {
      layout: newLayout,
      useShortDescription: useShortDesc,
      useExtendedDescription: true
    })

    // If content size changed, adapt content for this slide
    if (prevConfig?.contentSize !== newConfig?.contentSize) {
      setIsAdapting(true)
      try {
        const response = await fetch("/api/adapt-content", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            slides: [currentSlideData],
            layout: newLayout,
            topic: initialData.topic,
          }),
        })

        if (response.ok) {
          const data = await response.json()
          if (data.slides && data.slides[0]) {
            updateSlide(currentSlide, {
              ...data.slides[0],
              layout: newLayout,
              useShortDescription: useShortDesc,
              useExtendedDescription: true,
              backgroundImageUrl: currentSlideData.backgroundImageUrl,
            })
          }
        }
      } catch (error) {
        console.error("Failed to adapt content:", error)
      } finally {
        setIsAdapting(false)
      }
    }
  }

  const shuffleAllLayouts = () => {
    setSlides(assignSlideLayouts(slides))
  }

  const addSlide = () => {
    const newSlide: CarouselSlide = {
      id: `slide-${Date.now()}`,
      heading: "New Slide",
      body: "Add your content here...",
      bodyShort: "Add content...",
      bodyLong: "Add your detailed content here. This space is perfect for longer descriptions and explanations.",
      suggested_image: "A professional, modern image related to your topic",
      tone: "educational",
      min_text_version: "",
      max_text_version: "",
      layout: "centered",
      useExtendedDescription: false,
    }

    // Insert after current slide
    const newSlides = [...slides]
    newSlides.splice(currentSlide + 1, 0, newSlide)
    setSlides(newSlides)
    setCurrentSlide(currentSlide + 1)
  }

  const deleteSlide = () => {
    if (slides.length <= 1) {
      alert("Cannot delete the last slide")
      return
    }

    const newSlides = slides.filter((_, index) => index !== currentSlide)
    setSlides(newSlides)

    // Adjust current slide index if needed
    if (currentSlide >= newSlides.length) {
      setCurrentSlide(newSlides.length - 1)
    }
  }

  const handleExport = async () => {
    const exportData = {
      topic: initialData.topic,
      slides,
      theme,
    }
    await navigator.clipboard.writeText(JSON.stringify(exportData, null, 2))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const exportData = {
      topic: initialData.topic,
      slides,
      theme,
    }
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `carousel-${initialData.topic.toLowerCase().replace(/\s+/g, "-")}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const currentSlideData = slides[currentSlide]
  const currentLayout = currentSlideData.layout || "centered"

  return (
    <div className="min-h-screen bg-muted/30 flex">
      {/* Left Sidebar */}
      <div
        className={`bg-background border-r transition-all duration-300 flex flex-col ${sidebarCollapsed ? 'w-0 overflow-hidden' : 'w-[360px]'
          }`}
      >
        {/* Sidebar Content */}
        <div className="flex-1 flex flex-col min-h-0">
          <Tabs defaultValue="content" className="flex-1 flex flex-col min-h-0">
            {/* Tab Navigation */}
            <div className="p-4 pb-0">
              <TabsList className="w-full bg-muted/50 p-1 rounded-full">
                <TabsTrigger
                  value="content"
                  className="flex-1 rounded-full data-[state=active]:bg-background data-[state=active]:shadow-sm"
                >
                  <FileText className="h-4 w-4 mr-2" />
                  Content
                </TabsTrigger>
                <TabsTrigger
                  value="settings"
                  className="flex-1 rounded-full data-[state=active]:bg-background data-[state=active]:shadow-sm"
                >
                  <Settings className="h-4 w-4 mr-2" />
                  Settings
                </TabsTrigger>
                <TabsTrigger
                  value="brand"
                  className="flex-1 rounded-full data-[state=active]:bg-background data-[state=active]:shadow-sm"
                >
                  <User className="h-4 w-4 mr-2" />
                  Brand
                </TabsTrigger>
              </TabsList>
            </div>

            {/* Scrollable Content Area */}
            <ScrollArea className="flex-1">
              <div className="p-4 space-y-4">
                <TabsContent value="content" className="mt-0 space-y-4 m-0">
                  {/* Content Edit Section */}
                  <Card className="shadow-sm">
                    <CardContent className="p-4 space-y-4">
                      <h3 className="text-sm font-semibold text-primary">Content Edit</h3>

                      {/* Title Toggle */}
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <Label htmlFor="title-toggle" className="font-medium">Title</Label>
                          <Switch
                            id="title-toggle"
                            checked={titleEnabled}
                            onCheckedChange={setTitleEnabled}
                          />
                        </div>
                        {titleEnabled && (
                          <Input
                            value={currentSlideData.heading}
                            onChange={(e) => updateSlide(currentSlide, { heading: e.target.value })}
                            className="bg-muted/30"
                          />
                        )}
                      </div>

                      {/* Description Toggle */}
                      <div className="space-y-3">
                        <div className="flex items-center justify-between">
                          <Label htmlFor="description-toggle" className="font-medium">Description</Label>
                          <Switch
                            id="description-toggle"
                            checked={descriptionEnabled}
                            onCheckedChange={setDescriptionEnabled}
                          />
                        </div>

                        {descriptionEnabled && (
                          <div className="space-y-3">
                            {/* Version Selector */}
                            <div className="flex gap-1 p-1 bg-muted/50 rounded-lg">
                              <Button
                                type="button"
                                size="sm"
                                variant={currentSlideData.useShortDescription !== false ? "default" : "ghost"}
                                className="flex-1 h-7 text-xs"
                                onClick={() => updateSlide(currentSlide, {
                                  useShortDescription: true,
                                  useExtendedDescription: true
                                })}
                              >
                                Short
                              </Button>
                              <Button
                                type="button"
                                size="sm"
                                variant={currentSlideData.useShortDescription === false ? "default" : "ghost"}
                                className="flex-1 h-7 text-xs"
                                onClick={() => updateSlide(currentSlide, {
                                  useShortDescription: false,
                                  useExtendedDescription: true
                                })}
                              >
                                Long
                              </Button>
                            </div>

                            <div className="space-y-1.5">
                              <Label htmlFor="bodyShort" className="text-xs text-muted-foreground">Short Version</Label>
                              <Textarea
                                id="bodyShort"
                                value={currentSlideData.bodyShort || currentSlideData.body || ""}
                                onChange={(e) => updateSlide(currentSlide, {
                                  bodyShort: e.target.value,
                                  body: e.target.value,
                                  useExtendedDescription: true
                                })}
                                placeholder="Concise version for compact layouts..."
                                className="bg-muted/30 min-h-[60px] text-sm"
                              />
                            </div>
                            <div className="space-y-1.5">
                              <Label htmlFor="bodyLong" className="text-xs text-muted-foreground">Long Version</Label>
                              <Textarea
                                id="bodyLong"
                                value={currentSlideData.bodyLong || ""}
                                onChange={(e) => updateSlide(currentSlide, {
                                  bodyLong: e.target.value,
                                  useExtendedDescription: true
                                })}
                                placeholder="Detailed version for standard layouts..."
                                className="bg-muted/30 min-h-[100px] text-sm"
                              />
                            </div>
                          </div>
                        )}
                      </div>
                    </CardContent>
                  </Card>

                  {/* Image Generation Section */}
                  <Card className="shadow-sm">
                    <CardContent className="p-4 space-y-3">
                      <h3 className="text-sm font-semibold text-primary">Slide Images</h3>
                      <div className="space-y-2">
                        <Label htmlFor="image" className="text-xs text-muted-foreground">Image Generation Prompt</Label>
                        <Textarea
                          id="image"
                          value={currentSlideData.suggested_image}
                          onChange={(e) => updateSlide(currentSlide, { suggested_image: e.target.value })}
                          className="text-sm min-h-[100px] resize-y"
                          placeholder="Describe the image you want to generate..."
                        />
                      </div>
                      <div className="flex gap-2">
                        {currentSlideData.backgroundImageUrl ? (
                          <>
                            <Button
                              variant="outline"
                              size="sm"
                              className="flex-1"
                              onClick={() => generateBackgroundImage(currentSlide)}
                              disabled={currentSlideData.isGeneratingImage}
                            >
                              {currentSlideData.isGeneratingImage ? (
                                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                              ) : (
                                <ImageIcon className="h-4 w-4 mr-2" />
                              )}
                              Regenerate
                            </Button>
                            <Button variant="outline" size="sm" onClick={() => removeBackgroundImage(currentSlide)}>
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </>
                        ) : (
                          <Button
                            variant="outline"
                            size="sm"
                            className="w-full"
                            onClick={() => generateBackgroundImage(currentSlide)}
                            disabled={currentSlideData.isGeneratingImage}
                          >
                            {currentSlideData.isGeneratingImage ? (
                              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                            ) : (
                              <Sparkles className="h-4 w-4 mr-2" />
                            )}
                            Generate Image
                          </Button>
                        )}
                      </div>
                    </CardContent>
                  </Card>

                  {/* Custom Text Section */}
                  <Card className="shadow-sm">
                    <CardContent className="p-4 space-y-3">
                      <div className="flex items-center justify-between">
                        <h3 className="text-sm font-semibold text-primary flex items-center gap-2">
                          <Type className="h-4 w-4" />
                          Custom Text
                        </h3>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            const newText: CustomText = {
                              id: `text-${Date.now()}`,
                              text: "Your text here",
                              x: 50,
                              y: 50,
                              fontSize: "base",
                              fontWeight: "normal",
                              color: "heading",
                            }
                            updateSlide(currentSlide, {
                              customTexts: [...(currentSlideData.customTexts || []), newText],
                            })
                          }}
                        >
                          <Plus className="h-4 w-4 mr-1" />
                          Add Text
                        </Button>
                      </div>

                      {currentSlideData.customTexts && currentSlideData.customTexts.length > 0 ? (
                        <div className="space-y-3">
                          {currentSlideData.customTexts.map((customText, index) => (
                            <div key={customText.id} className="p-3 bg-muted/30 rounded-lg space-y-3">
                              <div className="flex items-center justify-between">
                                <span className="text-xs font-medium text-muted-foreground">Text {index + 1}</span>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-6 w-6 text-destructive"
                                  onClick={() => {
                                    updateSlide(currentSlide, {
                                      customTexts: currentSlideData.customTexts?.filter((t) => t.id !== customText.id),
                                    })
                                  }}
                                >
                                  <Trash2 className="h-3 w-3" />
                                </Button>
                              </div>

                              <Input
                                value={customText.text}
                                onChange={(e) => {
                                  updateSlide(currentSlide, {
                                    customTexts: currentSlideData.customTexts?.map((t) =>
                                      t.id === customText.id ? { ...t, text: e.target.value } : t
                                    ),
                                  })
                                }}
                                placeholder="Enter your text..."
                                className="bg-background text-sm"
                              />

                              <p className="text-xs text-muted-foreground italic">
                                Click on text in preview and use arrow keys to move
                              </p>

                              <div className="grid grid-cols-3 gap-2">
                                <div className="space-y-1">
                                  <Label className="text-xs">Size</Label>
                                  <Select
                                    value={customText.fontSize}
                                    onValueChange={(value: CustomText["fontSize"]) => {
                                      updateSlide(currentSlide, {
                                        customTexts: currentSlideData.customTexts?.map((t) =>
                                          t.id === customText.id ? { ...t, fontSize: value } : t
                                        ),
                                      })
                                    }}
                                  >
                                    <SelectTrigger className="h-8 text-xs">
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                      <SelectItem value="sm">Small</SelectItem>
                                      <SelectItem value="base">Normal</SelectItem>
                                      <SelectItem value="lg">Large</SelectItem>
                                      <SelectItem value="xl">XL</SelectItem>
                                      <SelectItem value="2xl">2XL</SelectItem>
                                      <SelectItem value="3xl">3XL</SelectItem>
                                    </SelectContent>
                                  </Select>
                                </div>
                                <div className="space-y-1">
                                  <Label className="text-xs">Weight</Label>
                                  <Select
                                    value={customText.fontWeight}
                                    onValueChange={(value: CustomText["fontWeight"]) => {
                                      updateSlide(currentSlide, {
                                        customTexts: currentSlideData.customTexts?.map((t) =>
                                          t.id === customText.id ? { ...t, fontWeight: value } : t
                                        ),
                                      })
                                    }}
                                  >
                                    <SelectTrigger className="h-8 text-xs">
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                      <SelectItem value="normal">Normal</SelectItem>
                                      <SelectItem value="medium">Medium</SelectItem>
                                      <SelectItem value="semibold">Semibold</SelectItem>
                                      <SelectItem value="bold">Bold</SelectItem>
                                      <SelectItem value="black">Black</SelectItem>
                                    </SelectContent>
                                  </Select>
                                </div>
                                <div className="space-y-1">
                                  <Label className="text-xs">Color</Label>
                                  <Select
                                    value={customText.color}
                                    onValueChange={(value: CustomText["color"]) => {
                                      updateSlide(currentSlide, {
                                        customTexts: currentSlideData.customTexts?.map((t) =>
                                          t.id === customText.id ? { ...t, color: value } : t
                                        ),
                                      })
                                    }}
                                  >
                                    <SelectTrigger className="h-8 text-xs">
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                      <SelectItem value="heading">Heading</SelectItem>
                                      <SelectItem value="text">Text</SelectItem>
                                      <SelectItem value="accent">Accent</SelectItem>
                                      <SelectItem value="white">White</SelectItem>
                                      <SelectItem value="black">Black</SelectItem>
                                    </SelectContent>
                                  </Select>
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <p className="text-xs text-muted-foreground text-center py-2">
                          No custom text added. Click "Add Text" to add custom text to your slide.
                        </p>
                      )}
                    </CardContent>
                  </Card>

                </TabsContent>

                <TabsContent value="settings" className="mt-0 space-y-4 m-0">
                  {/* Theme Section */}
                  <Card className="shadow-sm">
                    <CardContent className="p-4">
                      <h3 className="text-sm font-semibold text-primary mb-4">Theme</h3>
                      <ThemePicker currentTheme={theme} onThemeChange={setTheme} />
                    </CardContent>
                  </Card>

                  {/* Layout Section */}
                  <Card className="shadow-sm">
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="text-sm font-semibold text-primary">Layout</h3>
                        <Button variant="ghost" size="sm" onClick={shuffleAllLayouts}>
                          <Shuffle className="h-4 w-4 mr-2" />
                          Shuffle All
                        </Button>
                      </div>
                      <p className="text-xs text-muted-foreground mb-4">
                        {currentSlide === 0
                          ? "First slide - Diagonal Split recommended"
                          : currentSlide === slides.length - 1
                            ? "Last slide - Centered/Card best for CTAs"
                            : "Middle slide - Various layouts work well"}
                      </p>
                      <LayoutPicker currentLayout={currentLayout} onLayoutChange={handleSlideLayoutChange} theme={theme} />
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="brand" className="mt-0 space-y-4 m-0">
                  <Card className="shadow-sm">
                    <CardContent className="p-4 space-y-4">
                      <h3 className="text-sm font-semibold text-primary">Brand Settings</h3>

                      <div className="space-y-2">
                        <Label htmlFor="brandName">Name</Label>
                        <Input
                          id="brandName"
                          value={brandName}
                          onChange={(e) => setBrandName(e.target.value)}
                          placeholder="Your Name"
                        />
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="brandHandle">Handle / Website</Label>
                        <Input
                          id="brandHandle"
                          value={brandHandle}
                          onChange={(e) => setBrandHandle(e.target.value)}
                          placeholder="@YourHandle / www.YourWebsite.com"
                        />
                      </div>

                      <div className="space-y-2">
                        <Label>Profile Image</Label>
                        <div className="flex items-center gap-3">
                          {brandImage ? (
                            <div className="relative">
                              <img
                                src={brandImage}
                                alt="Brand"
                                className="w-12 h-12 rounded-full object-cover"
                              />
                              <Button
                                variant="destructive"
                                size="icon"
                                className="absolute -top-1 -right-1 h-5 w-5"
                                onClick={() => setBrandImage(null)}
                              >
                                <Trash2 className="h-3 w-3" />
                              </Button>
                            </div>
                          ) : (
                            <div className="w-12 h-12 rounded-full bg-muted flex items-center justify-center">
                              <User className="h-6 w-6 text-muted-foreground" />
                            </div>
                          )}
                          <Input
                            type="file"
                            accept="image/*"
                            className="flex-1"
                            onChange={(e) => {
                              const file = e.target.files?.[0]
                              if (file) {
                                const reader = new FileReader()
                                reader.onloadend = () => {
                                  setBrandImage(reader.result as string)
                                }
                                reader.readAsDataURL(file)
                              }
                            }}
                          />
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              </div>
            </ScrollArea>
          </Tabs>
        </div>
      </div>

      {/* Collapse Button */}
      <button
        onClick={() => setSidebarCollapsed(!sidebarCollapsed)}
        className="absolute left-0 top-1/2 -translate-y-1/2 z-50 bg-background border rounded-r-lg p-2 shadow-md hover:bg-muted transition-all"
        style={{ left: sidebarCollapsed ? 0 : '360px' }}
      >
        {sidebarCollapsed ? (
          <PanelLeft className="h-4 w-4" />
        ) : (
          <PanelLeftClose className="h-4 w-4" />
        )}
      </button>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col min-h-screen">
        {/* Top Toolbar */}
        <div className="sticky top-0 z-[60] bg-background border-b">
          <div className="px-6 py-3 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" onClick={onBack}>
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
              <div>
                <h1 className="font-semibold">{initialData.topic}</h1>
                <p className="text-xs text-muted-foreground">{slides.length} slides</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {/* Save status */}
              <div className="flex items-center gap-2 text-sm text-muted-foreground mr-2">
                {isSaving ? (
                  <>
                    <Cloud className="h-4 w-4 animate-pulse text-primary" />
                    <span className="hidden sm:inline">Saving...</span>
                  </>
                ) : lastSaved ? (
                  <>
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="hidden sm:inline">Saved</span>
                  </>
                ) : null}
              </div>

              {/* Action buttons */}
              <Button variant="outline" size="icon" onClick={handleExport} title="Copy JSON">
                {copied ? <Check className="h-4 w-4" /> : <Save className="h-4 w-4" />}
              </Button>
              <Button variant="outline" size="icon" title="Undo">
                <Undo className="h-4 w-4" />
              </Button>
              <Button variant="outline" size="icon" title="Redo">
                <Redo className="h-4 w-4" />
              </Button>
              <Button variant="outline" size="icon" onClick={handleDownload} title="Download">
                <Share2 className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        {/* Preview Area */}
        <div className="flex-1 p-6 overflow-auto">
          <div className="flex flex-col items-center relative">
            {isAdapting && (
              <div className="absolute inset-0 flex items-center justify-center bg-background/50 backdrop-blur-sm rounded-2xl z-10">
                <div className="flex flex-col items-center gap-2">
                  <Sparkles className="h-8 w-8 animate-pulse text-primary" />
                  <span className="text-sm font-medium">Adapting content for new layout...</span>
                </div>
              </div>
            )}
            <SlidePreview
              slide={currentSlideData}
              theme={theme}
              layout={currentLayout}
              slideNumber={currentSlide + 1}
              totalSlides={slides.length}
              brandName={brandName}
              brandHandle={brandHandle}
              brandImage={brandImage}
              onBrandNameChange={setBrandName}
              onBrandHandleChange={setBrandHandle}
              onBrandImageChange={setBrandImage}
              onCustomTextMove={(textId, x, y) => {
                updateSlide(currentSlide, {
                  customTexts: currentSlideData.customTexts?.map((t) =>
                    t.id === textId ? { ...t, x, y } : t
                  ),
                })
              }}
            />

            {/* Navigation */}
            <div className="flex items-center gap-4 mt-6">
              <Button
                variant="outline"
                size="icon"
                onClick={() => goToSlide(currentSlide - 1)}
                disabled={currentSlide === 0}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>

              <div className="flex gap-2">
                {slides.map((slide, index) => (
                  <button
                    key={index}
                    onClick={() => goToSlide(index)}
                    className={`h-2 rounded-full transition-all relative ${index === currentSlide
                      ? "w-8 bg-primary"
                      : "w-2 bg-muted-foreground/30 hover:bg-muted-foreground/50"
                      }`}
                    aria-label={`Go to slide ${index + 1}`}
                  >
                    {slide.backgroundImageUrl && (
                      <span className="absolute -top-1 -right-1 w-2 h-2 bg-green-500 rounded-full" />
                    )}
                  </button>
                ))}
              </div>

              <Button
                variant="outline"
                size="icon"
                onClick={() => goToSlide(currentSlide + 1)}
                disabled={currentSlide === slides.length - 1}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>

              {/* Slide management buttons */}
              <div className="flex items-center gap-2 ml-4 border-l pl-4">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={addSlide}
                  className="gap-1"
                >
                  <Plus className="h-4 w-4" />
                  Add
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={deleteSlide}
                  disabled={slides.length <= 1}
                  className="gap-1 text-destructive hover:text-destructive"
                >
                  <Minus className="h-4 w-4" />
                  Delete
                </Button>
              </div>
            </div>
          </div>

          {/* Slide Thumbnails */}
          <div className="mt-6">
            <ScrollArea className="w-full">
              <div className="flex gap-3 pb-4 justify-center">
                {slides.map((slide, index) => (
                  <button
                    key={index}
                    onClick={() => goToSlide(index)}
                    className={`flex-shrink-0 w-32 p-3 rounded-lg text-left transition-all relative ${index === currentSlide
                      ? "ring-2 ring-primary bg-background shadow-md"
                      : "bg-background/60 hover:bg-background"
                      }`}
                  >
                    {slide.backgroundImageUrl && (
                      <span className="absolute top-2 right-2">
                        <ImageIcon className="h-3 w-3 text-green-500" />
                      </span>
                    )}
                    <div className="text-xs font-medium text-muted-foreground mb-1">Slide {index + 1}</div>
                    <div className="text-sm font-medium line-clamp-2">{slide.heading}</div>
                    <div className="text-xs text-muted-foreground mt-1 truncate">
                      {LAYOUT_OPTIONS.find((l) => l.id === slide.layout)?.name || "Centered"}
                    </div>
                  </button>
                ))}
              </div>
            </ScrollArea>
          </div>
        </div>
      </div>
    </div>
  )
}
